-- Extend artifacts table to support agent-generated content
-- This migration adds support for project ideas and email templates

-- Drop existing type constraint
ALTER TABLE artifacts 
DROP CONSTRAINT IF EXISTS artifacts_type_check;

-- Add new constraint with agent types
ALTER TABLE artifacts 
ADD CONSTRAINT artifacts_type_check 
CHECK (type IN (
    'pitch_deck', 
    'product_roadmap', 
    'technical_doc', 
    'marketing_copy', 
    'project_idea',      -- Generated by Project Idea Generator Tool
    'email_template',    -- Generated by Email Template Creator Tool
    'other'
));

-- Create email campaigns table for tracking outreach
CREATE TABLE IF NOT EXISTS email_campaigns (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    created_by UUID NOT NULL REFERENCES user_profiles(id) ON DELETE RESTRICT,
    project_artifact_id UUID REFERENCES artifacts(id) ON DELETE SET NULL,
    email_artifact_id UUID REFERENCES artifacts(id) ON DELETE SET NULL,
    recipient_email TEXT,
    recipient_name TEXT,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'delivered', 'opened', 'replied', 'bounced')),
    sent_at TIMESTAMP WITH TIME ZONE,
    opened_at TIMESTAMP WITH TIME ZONE,
    replied_at TIMESTAMP WITH TIME ZONE,
    campaign_metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for email campaigns
CREATE INDEX IF NOT EXISTS idx_email_campaigns_company_id ON email_campaigns(company_id);
CREATE INDEX IF NOT EXISTS idx_email_campaigns_created_by ON email_campaigns(created_by);
CREATE INDEX IF NOT EXISTS idx_email_campaigns_project_artifact_id ON email_campaigns(project_artifact_id);
CREATE INDEX IF NOT EXISTS idx_email_campaigns_email_artifact_id ON email_campaigns(email_artifact_id);
CREATE INDEX IF NOT EXISTS idx_email_campaigns_status ON email_campaigns(status);
CREATE INDEX IF NOT EXISTS idx_email_campaigns_sent_at ON email_campaigns(sent_at);

-- Add updated_at trigger for email campaigns
CREATE TRIGGER update_email_campaigns_updated_at 
    BEFORE UPDATE ON email_campaigns
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Enable RLS on email campaigns
ALTER TABLE email_campaigns ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for email_campaigns
CREATE POLICY "email_campaigns_no_anon_access" ON email_campaigns
  AS RESTRICTIVE
  FOR ALL
  TO anon
  USING (false)
  WITH CHECK (false);

CREATE POLICY "email_campaigns_select_company" ON email_campaigns
  FOR SELECT
  TO authenticated
  USING (company_id = public.get_user_company_id());

CREATE POLICY "email_campaigns_insert_own_company" ON email_campaigns
  FOR INSERT
  TO authenticated
  WITH CHECK (
    company_id = public.get_user_company_id()
    AND created_by = public.get_current_user_id()
  );

CREATE POLICY "email_campaigns_update_own" ON email_campaigns
  FOR UPDATE
  TO authenticated
  USING (created_by = public.get_current_user_id())
  WITH CHECK (created_by = public.get_current_user_id());

CREATE POLICY "email_campaigns_delete_own" ON email_campaigns
  FOR DELETE
  TO authenticated
  USING (created_by = public.get_current_user_id());

CREATE POLICY "email_campaigns_service_role_all" ON email_campaigns
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Add helpful comments
COMMENT ON TABLE email_campaigns IS 'Email campaigns linking project artifacts to outreach emails';
COMMENT ON COLUMN email_campaigns.project_artifact_id IS 'Reference to the project idea artifact that was completed';
COMMENT ON COLUMN email_campaigns.email_artifact_id IS 'Reference to the generated email template artifact';
COMMENT ON COLUMN email_campaigns.status IS 'Campaign status: draft, sent, delivered, opened, replied, bounced';
COMMENT ON COLUMN email_campaigns.campaign_metadata IS 'Additional metadata about the email campaign';

-- Update artifact type comments
COMMENT ON COLUMN artifacts.type IS 'Type of document: pitch_deck, product_roadmap, technical_doc, marketing_copy, project_idea, email_template, other';

-- Add success message
DO $$
BEGIN
  RAISE NOTICE 'Successfully extended artifacts table for agent-generated content';
  RAISE NOTICE 'Added support for project_idea and email_template artifact types';
  RAISE NOTICE 'Created email_campaigns table with proper RLS policies';
END $$;